spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for Auth Service
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # Route for User Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # Route for Product Service
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        # Route for Order Service
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

      # Optional: Global Filters
      default-filters:
        - AddResponseHeader=X-Response-Time, %{response-time}ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL