spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/dev_order_db
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
    fetch-registry: true
    register-with-eureka: true